import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.scss";
import { Header } from "../../components/header/Header";
import { Footer } from "../../components/footer/Footer";

const urbanist = Urbanist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "InCosmos",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={urbanist.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
